CREATE TABLE `blog`.`pub_user` (
  `user_id` VARCHAR(50) NOT NULL COMMENT '用户id',
  `user_name` VARCHAR(100) NOT NULL COMMENT '用户名称',
  `bill_code` VARCHAR(20) NOT NULL COMMENT '编码',
  `nick_name` VARCHAR(50) NULL COMMENT '尼称',
  `mail` VARCHAR(100) NULL COMMENT '邮箱',
  `phone` VARCHAR(50) NULL COMMENT '手机号',
  `birthday` DATE NULL COMMENT '生日 ',
  `tmp_int1` INT NULL,
  `tmp_int2` INT NULL,
  `tmp_int3` INT NULL,
  `tmp_int4` INT NULL,
  `tmp_var1` VARCHAR(50) NULL,
  `tmp_var2` VARCHAR(50) NULL,
  `tmp_var3` VARCHAR(50) NULL,
  `tmp_var4` VARCHAR(50) NULL,
  `ts` VARCHAR(20) NULL COMMENT '时间戳',
  `sex` VARCHAR(10) NULL COMMENT '性别',
  `pic_head` VARCHAR(100) NULL COMMENT '头像',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `bill_code_UNIQUE` (`bill_code` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC));
